spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Netflix Ribbon 대신 Spring Cloud LoadBalancer 사용
  ### 공통 DB 설정
  datasource:
    url: jdbc:postgresql://athenhub-db.cj42m84s0lzn.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}        # EC2 환경 변수나 GitHub Actions에서 주입
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update              # 개발 중에는 create / create-drop 가능, 나중에 validate/none 권장
    properties:
      hibernate:
        default_schema: ${athenhub.schema:public}  # 👉 각 서비스가 이 값을 override
    show-sql: true
    open-in-view: false

feign:
  client:
    config:
      default: # 모든 클라이언트에 적용
        connectTimeout: 5000 # 연결 시도(소켓 연결) 타임아웃: 밀리초 단위. 5000ms = 5초
        readTimeout: 5000 # 서버 응답을 기다리는 읽기 타임아웃:
        loggerLevel: full # 로거 레벨: NONE, BASIC, HEADERS, FULL 중 하나.

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
  endpoint:
    prometheus:
      enabled: true