spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hub/**
          filters:
            - 'RewritePath=/hub/(?<path>.*), /\${path}'
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - 'RewritePath=/product/(?<path>.*), /\${path}'
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**
          filters:
            - 'RewritePath=/member/(?<path>.*), /\${path}'
