spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hub/**
          filters:
            - 'RewritePath=/hubs/(?<path>.*), /\${path}'
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - 'RewritePath=/products/(?<path>.*), /\${path}'
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/hub/**
          filters:
            - 'RewritePath=/members/(?<path>.*), /\${path}'
