server:
  port: 9012

spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/v1/member/**
          filters:
            - 'RewritePath=/v1/member/(?<path>.*), /\${path}'
  datasource:
    url: jdbc:postgresql://athenhub-db.cj42m84s0lzn.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: athenhub123
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: member_service # 이 서비스에서 기본으로 사용할 DB 스키마 이름
